# Step 1: Creating the dataset

***1. Our target is to determine the motor type manufactured by the motor companies***

***2. First, we need to create a synthetic dataset. which can be defined as follows:-***

a. Each **row** represents one company/brand.
b.  Each **column** represents a measurable or interpretable vehicle-related property.
c.  To keep the dataset simple, ordinal values (size, weight, power, length) are encoded numerically as:

  - **0 = low**
  - **1 = medium**
  - **2 = high**

## Variables included

1. **Passenger_Capacity**: how strongly the brand is associated with vehicles carrying more people
2. **Cargo_Capacity**: how strongly the brand is associated with goods/commercial load transport
3. **Luxury_Level**: how premium the brand is
4. **Performance**: how strongly the brand is associated with high-performance vehicles
5. **Commercial_Focus**: how much the brand is connected to commercial-use vehicles
6. **Urban_Compactness**: how much the brand is associated with compact city vehicles
7. **Two_Wheeler_Focus**: whether the brand is mainly associated with scooters or two-wheelers
8. **Price_Level**: an approximate overall market price positioning

## Detailed target of the exercise

Its purpose is not to perfectly describe real-world car companies, but to create a structured example where we can later apply factor analysis and see whether hidden latent factors emerge.

For example, possible latent factors may correspond to ideas such as:

1. luxury/performance
2. commercial utility
3. Private mobility
4. Two-wheeler mobility

## Our sample space is below:-

In [10]:
#import pandas as pd

## Codes:
##low = 0, medium = 1, high = 2

#data = {
#    "Company": [
#        "BMW", "Audi", "Tata", "Nissan", "Honda",
#        "Toyota", "Mercedes", "Vespa", "Bugatti"
#    ],
#    "Passenger_Capacity": [1, 1, 2, 1, 1, 2, 1, 0, 0],
#    "Cargo_Capacity":     [0, 0, 2, 1, 0, 1, 0, 0, 0],
#    "Luxury_Level":       [2, 2, 0, 1, 1, 1, 2, 0, 2],
#    "Performance":        [2, 1, 0, 1, 1, 1, 2, 0, 2],
#    "Commercial_Focus":   [0, 0, 2, 1, 0, 1, 0, 0, 0],
#    "Urban_Compactness":  [1, 1, 0, 1, 1, 1, 0, 2, 0],
#    "Two_Wheeler_Focus":  [0, 0, 0, 0, 0, 0, 0, 2, 0],
#    "Price_Level":        [2, 2, 0, 1, 1, 1, 2, 0, 2]
#}

#df = pd.DataFrame(data)
#df = df.set_index("Company")

#df

In [15]:
import pandas as pd
from IPython.display import display

# Codes:
# low = 0, medium = 1, high = 2

data = {
    "Company": [
        "BMW", "Audi", "Mercedes", "Ford", "Toyota", "Honda",
        "Hyundai", "Tata", "Mahindra", "General Motors",
        "Vespa", "TVS", "Yamaha", "Bugatti", "Ferrari", "Lamborghini"
    ],
    "Passenger_Capacity": [1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0],
    "Cargo_Capacity":     [0, 0, 0, 1, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0],
    "Luxury_Level":       [2, 2, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 2],
    "Performance":        [2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 2, 2],
    "Commercial_Focus":   [0, 0, 0, 1, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0],
    "Urban_Compactness":  [1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 1, 0, 0, 0],
    "Two_Wheeler_Focus":  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0],
    "Price_Level":        [2, 2, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 2, 2, 2]
}

df = pd.DataFrame(data)
df = df.set_index("Company")

display(df)

,Passenger_Capacity,Cargo_Capacity,Luxury_Level,Performance,Commercial_Focus,Urban_Compactness,Two_Wheeler_Focus,Price_Level
Company,,,,,,,,
BMW,1,0,2,2,0,1,0,2
Audi,1,0,2,1,0,1,0,2
Mercedes,1,0,2,2,0,0,0,2
Ford,2,1,1,1,1,1,0,1
Toyota,2,1,1,1,1,1,0,1
Honda,1,0,1,1,0,1,0,1
Hyundai,1,0,1,1,0,1,0,1
Tata,2,2,0,0,2,0,0,0
Mahindra,2,2,0,1,2,0,0,0
General Motors,2,1,1,1,1,1,0,1
Vespa,0,0,0,0,0,2,2,0
TVS,0,0,0,1,0,2,2,0
Yamaha,0,0,0,1,0,1,2,1
Bugatti,0,0,2,2,0,0,0,2
Ferrari,0,0,2,2,0,0,0,2
Lamborghini,0,0,2,2,0,0,0,2

# This section is for academic purposes; if you seek details, as you should because you are a scientist (If you did not laugh, you definitely are a scientist)
## Step 2: Mathematical formulation of factor analysis

Factor analysis assumes that the observed data can be explained by a smaller number of hidden variables called **latent factors**.

A common matrix form of the factor model is:

$$
X = L F + \varepsilon
$$

where:

* $X$ is the matrix of **observed variables**
* $L$ is the **loading matrix**
* $F$ is the matrix of **factor scores**
* $\varepsilon$ is the **residual/error matrix**

In element-wise form, this can be written as:

$$
x_{ij} = \lambda_{j1} f_{i1} + \lambda_{j2} f_{i2} + \cdots + \lambda_{jk} f_{ik} + \varepsilon_{ij}
$$

or equivalently,

$$
x_{ij} = \sum_{m=1}^{k} f_{im}\lambda_{jm} + \varepsilon_{ij}
$$

## Interpretation of the symbols in our example

In this notebook:

* each **row** corresponds to one company/brand
* each **column** corresponds to one measured vehicle-related property

So the observed matrix $X$ is our company-by-feature table.

If we have:

* $n$ companies
* $p$ observed variables
* $k$ latent factors

then:
$$
X \in \mathbb{R}^{n \times p}, \qquad
F \in \mathbb{R}^{n \times k}, \qquad
L \in \mathbb{R}^{p \times k}, \qquad
\varepsilon \in \mathbb{R}^{n \times p}
$$


## In this dataset

We currently have:

* $n = 9$ companies
* $p = 8$ observed properties

Thus, our observed matrix \(X\) has dimension:

$$
X \in \mathbb{R}^{9 \times 8}
$$

The aim of factor analysis is to describe these 8 observed properties using a smaller number $k$ of latent factors.

For example, the analysis may reveal hidden factors such as:

1. luxury/performance
2. commercial utility
3. Private mobility
4. Two-wheeler mobility

These factors are not directly measured, but are inferred from the correlation structure of the observed variables, so our common factor space is $k=4$

In [16]:
import numpy as np

# Observed data matrix X
X = df.values

print("Observed data matrix X:")
print(X)

print("\nShape of X (n companies × p variables):", X.shape)

Observed data matrix X:
[[1 0 2 2 0 1 0 2]
 [1 0 2 1 0 1 0 2]
 [1 0 2 2 0 0 0 2]
 [2 1 1 1 1 1 0 1]
 [2 1 1 1 1 1 0 1]
 [1 0 1 1 0 1 0 1]
 [1 0 1 1 0 1 0 1]
 [2 2 0 0 2 0 0 0]
 [2 2 0 1 2 0 0 0]
 [2 1 1 1 1 1 0 1]
 [0 0 0 0 0 2 2 0]
 [0 0 0 1 0 2 2 0]
 [0 0 0 1 0 1 2 1]
 [0 0 2 2 0 0 0 2]
 [0 0 2 2 0 0 0 2]
 [0 0 2 2 0 0 0 2]]

Shape of X (n companies × p variables): (16, 8)

In [21]:
import pandas as pd

print("Original company-by-feature table:")
display(df)

factor_map = {
    1: ("luxury/performance", ["Luxury_Level", "Performance", "Price_Level"]),
    2: ("commercial_utility", ["Cargo_Capacity", "Commercial_Focus", "Passenger_Capacity"]),
    3: ("private_mobility", ["Passenger_Capacity", "Urban_Compactness", "Price_Level"]),
    4: ("two_wheeler_mobility", ["Two_Wheeler_Focus", "Urban_Compactness", "Price_Level"])
}

print("\nAvailable mobility preference options:")
print("1. Luxury / Performance")
print("2. Commercial Utility")
print("3. Private Mobility")
print("4. Two-Wheeler Mobility")

try:
    choice = int(input("\nEnter a number (1-4): ").strip())

    if choice in factor_map:
        factor_name, selected_features = factor_map[choice]

        print(f"\nSelected category: {factor_name}")
        print(f"Relevant features used: {selected_features}")

        result = df.copy()
        result["Score"] = result[selected_features].sum(axis=1)

        ranked = result.sort_values("Score", ascending=False)

        print("\nRanked companies based on the selected mobility factor:")
        display(ranked[selected_features + ["Score"]])

    else:
        print("Invalid option. Please enter a number from 1 to 4.")

except ValueError:
    print("Invalid input. Please enter an integer from 1 to 4.")

Original company-by-feature table:

,Passenger_Capacity,Cargo_Capacity,Luxury_Level,Performance,Commercial_Focus,Urban_Compactness,Two_Wheeler_Focus,Price_Level
Company,,,,,,,,
BMW,1,0,2,2,0,1,0,2
Audi,1,0,2,1,0,1,0,2
Mercedes,1,0,2,2,0,0,0,2
Ford,2,1,1,1,1,1,0,1
Toyota,2,1,1,1,1,1,0,1
Honda,1,0,1,1,0,1,0,1
Hyundai,1,0,1,1,0,1,0,1
Tata,2,2,0,0,2,0,0,0
Mahindra,2,2,0,1,2,0,0,0
General Motors,2,1,1,1,1,1,0,1
Vespa,0,0,0,0,0,2,2,0
TVS,0,0,0,1,0,2,2,0
Yamaha,0,0,0,1,0,1,2,1
Bugatti,0,0,2,2,0,0,0,2
Ferrari,0,0,2,2,0,0,0,2
Lamborghini,0,0,2,2,0,0,0,2

Available mobility preference options:
1. Luxury / Performance
2. Commercial Utility
3. Private Mobility
4. Two-Wheeler Mobility

Enter a number (1-4):  2

Selected category: commercial_utility
Relevant features used: ['Cargo_Capacity', 'Commercial_Focus', 'Passenger_Capacity']

Ranked companies based on the selected mobility factor:

                Cargo_Capacity  Commercial_Focus  Passenger_Capacity  Score
Company
Tata                         2                 2                   2      6
Mahindra                     2                 2                   2      6
Ford                         1                 1                   2      4
Toyota                       1                 1                   2      4
General Motors               1                 1                   2      4
BMW                          0                 0                   1      1
Audi                         0                 0                   1      1
Mercedes                     0                 0                   1      1
Honda                        0                 0                   1      1
Hyundai                      0                 0                   1      1
Vespa                        0                 0                   0      0
TVS                          0                 0                   0      0
Yamaha                       0                 0                   0      0
Bugatti                      0                 0                   0      0
Ferrari                      0                 0                   0      0
Lamborghini                  0                 0                   0      0